# Generated by Django 5.0.6 on 2024-06-26 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prosedyre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittel', models.CharField(max_length=255)),
                ('beskrivelse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProsedyreGjennomgang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullført', models.BooleanField(default=False)),
                ('fullført_dato', models.DateTimeField(blank=True, null=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('prosedyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosedyrer.prosedyre')),
            ],
        ),
        migrations.CreateModel(
            name='ProsedyrePunkt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beskrivelse', models.TextField()),
                ('rekkefolge', models.PositiveIntegerField()),
                ('prosedyre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prosedyrer.prosedyre')),
            ],
        ),
    ]
