# Generated by Django 5.0.6 on 2024-06-25 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('employee', 'Ansatt'), ('franchisee', 'Franchisee'), ('admin', 'Administrator')], default='employee', max_length=20),
        ),
    ]
