# Generated by Django 5.0.6 on 2024-06-26 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_key_metrics_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='key_metrics',
        ),
    ]
