# Generated by Django 5.0.6 on 2024-06-26 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_profile_key_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='key_metrics',
            field=models.JSONField(default=dict),
        ),
    ]
