# Generated by Django 5.0.6 on 2024-06-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_key_metrics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='key_metrics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
