# Generated by Django 4.2.12 on 2024-06-29 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Modul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('navn', models.CharField(max_length=100)),
                ('beskrivelse', models.TextField()),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moduler', to='kurs.kurs')),
            ],
        ),
        migrations.CreateModel(
            name='FullfortModul',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullfort_dato', models.DateTimeField(auto_now_add=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('modul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.modul')),
            ],
        ),
        migrations.CreateModel(
            name='FullfortKurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullfort_dato', models.DateTimeField(auto_now_add=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.kurs')),
            ],
        ),
    ]
