# Generated by Django 5.0.6 on 2024-06-25 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0002_remove_modul_innhold_modul_beskrivelse_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullfortmodul',
            name='bruker',
        ),
        migrations.AddField(
            model_name='fullfortmodul',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fullforte_moduler', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fullfortmodul',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fullfort_av', to='kurs.modul'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='navn',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='modul',
            name='navn',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='FullfortKurs',
        ),
    ]
