# Generated by Django 5.0.6 on 2024-06-25 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurs', '0003_remove_fullfortmodul_bruker_fullfortmodul_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fullfortmodul',
            name='user',
        ),
        migrations.AddField(
            model_name='fullfortmodul',
            name='bruker',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fullfortmodul',
            name='modul',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.modul'),
        ),
        migrations.AlterField(
            model_name='kurs',
            name='navn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modul',
            name='navn',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='FullfortKurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullfort_dato', models.DateTimeField(auto_now_add=True)),
                ('bruker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kurs.kurs')),
            ],
        ),
    ]
